version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ar-postgres
    environment:
      POSTGRES_DB: arscuptures
      POSTGRES_USER: aruser
      POSTGRES_PASSWORD: arpassword123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ar-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aruser -d arsculptures"]
      interval: 10s
      timeout: 5s
      retries: 5
  minio:
    image: minio/minio
    container_name: ar-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: very_secret_pass_lol
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks: 
      - ar-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  minio_data:
  
networks:
  ar-network:
    driver: bridge